name: Deploy on Develop Push

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run SSH commands on server
        env:
          SERVER_PASSWORD: ${{ secrets.SSH_KEY }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no {{ secrets.SERVER_USER }}@{{ secrets.SERVER_IP }} '
            cd /home/server/services/frontend/entity-generator-frontend &&
            docker compose build &&
            docker compose up -d
          '
